spring:
  # Spring JDBC configuration
  datasource:
    url:      jdbc:mariadb://localhost:3306/pizzamaker?serverTimezone=UTC
    username: ruslan
    password: master

  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage!
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false
properties:
  kithen:
    maxingredient: 2
    maxPizza: 10