DROP TABLE IF EXISTS ingredients;
CREATE TABLE IF NOT EXISTS ingredients (id INTEGER NOT NULL AUTO_INCREMENT, conditions VARCHAR(30), name  VARCHAR(30), taste  VARCHAR(30), PRIMARY KEY (id));
INSERT INTO ingredients(conditions, name, taste) VALUES ('FRESH','Сыр', 'SALTY');
INSERT INTO ingredients(conditions, name, taste) VALUES ('FRESH','Лук', 'BITTER');
INSERT INTO ingredients(conditions, name, taste) VALUES ('FRESH','Грибы', 'BLAND');
INSERT INTO ingredients(conditions, name, taste) VALUES ('CANNED_FOOD','Оливки', 'SALTY');
INSERT INTO ingredients(conditions, name, taste) VALUES ('CANNED_FOOD','Перец', 'SPICY');
INSERT INTO ingredients(conditions, name, taste) VALUES ('CANNED_FOOD','Кетчуп', 'SWEET');
INSERT INTO ingredients(conditions, name, taste) VALUES ('SOAKED','Креветки', 'SALTY');
INSERT INTO ingredients(conditions, name, taste) VALUES ('FRESH','Курица', 'SOUR');
INSERT INTO ingredients(conditions, name, taste) VALUES ('CANNED_FOOD','Ананас', 'SWEET');