DROP TABLE IF EXISTS recipe;
CREATE TABLE IF NOT EXISTS recipe (id INTEGER NOT NULL AUTO_INCREMENT, countIngredient INTEGER, PRIMARY KEY (id), FOREIGN KEY (ingredients_id) REFERENCES ingredients(id));
